/**
 * Visual identity for each character: palette, silhouette, weapon and headgear.
 *
 * Kept out of `types/brawl` on purpose — the simulation has no business knowing
 * what anybody looks like, and the renderer is the only consumer.
 */

import type { BrawlerId } from '../types/brawl';
import type { CharacterStyle } from './characterArt';

export const CHARACTER_STYLES: Record<BrawlerId, CharacterStyle> = {
  mira: {
    primary: '#7c3aed',
    secondary: '#3b2a63',
    accent: '#f0abfc',
    skin: '#e4a67a',
    hair: '#c084fc',
    build: 'medium',
    weapon: 'scattergun',
    headgear: 'hood',
    // A scavenger's cape: the one silhouette that trails behind her.
    back: 'cape',
    eyes: '#4c1d95',
  },
  rivet: {
    primary: '#dc2626',
    secondary: '#4b1d1d',
    accent: '#fca5a5',
    skin: '#f0c08a',
    hair: '#1f2937',
    build: 'light',
    weapon: 'twin_blasters',
    headgear: 'cap',
    back: 'drum',
    eyes: '#7f1d1d',
  },
  boulder: {
    primary: '#0369a1',
    secondary: '#1e3a5f',
    accent: '#38bdf8',
    skin: '#d99a63',
    hair: '#0c4a6e',
    build: 'heavy',
    weapon: 'gauntlets',
    headgear: 'mask',
    back: 'wings',
  },
  fuse: {
    primary: '#d97706',
    secondary: '#4a2c08',
    accent: '#fbbf24',
    skin: '#8d5524',
    hair: '#1c1917',
    build: 'medium',
    weapon: 'launcher',
    headgear: 'goggles',
    // Fuel bottles, so the artillery reads as artillery from behind too.
    back: 'tank',
    eyes: '#78350f',
  },
  thorn: {
    primary: '#15803d',
    secondary: '#14532d',
    accent: '#86efac',
    skin: '#4ade80',
    hair: '#166534',
    build: 'light',
    weapon: 'satchel',
    headgear: 'crest',
    back: 'pack',
    eyes: '#14532d',
  },
  wisp: {
    primary: '#0891b2',
    secondary: '#134e4a',
    accent: '#67e8f9',
    skin: '#d9c7a7',
    hair: '#0e7490',
    build: 'light',
    weapon: 'blades',
    headgear: 'hood',
    back: 'cape',
    eyes: '#0e7490',
  },
  molotof: {
    primary: '#c2410c',
    secondary: '#5a2208',
    accent: '#fb923c',
    skin: '#c98b5a',
    hair: '#431407',
    build: 'medium',
    weapon: 'flask',
    headgear: 'mask',
    back: 'tank',
  },
  ustabasi: {
    // Grey on grey, with the accent doing all the identifying work: the
    // silhouette has to read as the one carrying equipment, not a colour.
    primary: '#475569',
    secondary: '#1e293b',
    accent: '#facc15',
    skin: '#b47b50',
    hair: '#0f172a',
    build: 'heavy',
    weapon: 'toolgun',
    headgear: 'visor',
    back: 'pack',
  },
  nagme: {
    primary: '#be185d',
    secondary: '#500724',
    accent: '#fbcfe8',
    skin: '#e8b48c',
    hair: '#831843',
    build: 'light',
    weapon: 'horn',
    headgear: 'crest',
    back: 'coil',
    eyes: '#831843',
  },
  zirh: {
    primary: '#0f766e',
    secondary: '#042f2e',
    accent: '#5eead4',
    skin: '#a9693c',
    hair: '#134e4a',
    build: 'heavy',
    weapon: 'hammer',
    headgear: 'helm',
    back: 'drum',
  },
  karambol: {
    primary: '#4d7c0f',
    secondary: '#1a2e05',
    accent: '#bef264',
    skin: '#d6a672',
    hair: '#1a2e05',
    build: 'medium',
    weapon: 'cue',
    headgear: 'goggles',
    back: 'pack',
    eyes: '#365314',
  },
  fisilti: {
    primary: '#4338ca',
    secondary: '#1e1b4b',
    accent: '#a5b4fc',
    skin: '#e0c3a3',
    hair: '#312e81',
    build: 'light',
    weapon: 'daggers',
    headgear: 'mask',
    back: 'cape',
  },
  cengel: {
    primary: '#a16207',
    secondary: '#3b2308',
    accent: '#fde047',
    skin: '#c08457',
    hair: '#422006',
    build: 'medium',
    weapon: 'hook',
    headgear: 'cap',
    back: 'coil',
    eyes: '#713f12',
  },
  buz: {
    primary: '#0e7490',
    secondary: '#083344',
    accent: '#e0f2fe',
    skin: '#e6d5c3',
    hair: '#bae6fd',
    build: 'light',
    weapon: 'frost',
    headgear: 'crest',
    back: 'wings',
    eyes: '#0369a1',
  },
  bekci: {
    primary: '#b45309',
    secondary: '#451a03',
    accent: '#fcd34d',
    skin: '#e0b48a',
    hair: '#292524',
    build: 'medium',
    weapon: 'lantern',
    headgear: 'cap',
    back: 'pack',
    eyes: '#78350f',
  },
  kalkan: {
    primary: '#0369a1',
    secondary: '#0c4a6e',
    accent: '#bae6fd',
    skin: '#d9a77c',
    hair: '#1e3a5f',
    build: 'heavy',
    weapon: 'buckler',
    headgear: 'helm',
    back: 'cape',
    eyes: '#0c4a6e',
  },
  filiz: {
    primary: '#15803d',
    secondary: '#14532d',
    accent: '#bbf7d0',
    skin: '#a7d7a0',
    hair: '#4d7c0f',
    build: 'light',
    weapon: 'sprout',
    headgear: 'hood',
    back: 'wings',
    eyes: '#14532d',
  },
  sis: {
    primary: '#6d28d9',
    secondary: '#2e1065',
    accent: '#ddd6fe',
    skin: '#d8c3dc',
    hair: '#4c1d95',
    build: 'light',
    weapon: 'censer',
    headgear: 'mask',
    back: 'cape',
    eyes: '#4c1d95',
  },
  lumen: {
    primary: '#a16207',
    secondary: '#422006',
    accent: '#fef08a',
    skin: '#e8c39e',
    hair: '#fde68a',
    build: 'light',
    weapon: 'rifle',
    headgear: 'visor',
    back: 'coil',
    eyes: '#854d0e',
  },
  ors: {
    primary: '#9f1239',
    secondary: '#4c0519',
    accent: '#fda4af',
    skin: '#c98c62',
    hair: '#1c1917',
    build: 'heavy',
    weapon: 'axe',
    headgear: 'helm',
    back: 'drum',
    eyes: '#450a0a',
  },
  devir: {
    primary: '#c2410c',
    secondary: '#431407',
    accent: '#fed7aa',
    skin: '#e4a67a',
    hair: '#7c2d12',
    build: 'medium',
    weapon: 'boomerang',
    headgear: 'crest',
    back: 'none',
    eyes: '#7c2d12',
  },
  golge: {
    primary: '#3730a3',
    secondary: '#1e1b4b',
    accent: '#c7d2fe',
    skin: '#cbb7d6',
    hair: '#312e81',
    build: 'light',
    weapon: 'knives',
    headgear: 'hood',
    back: 'none',
    eyes: '#a5b4fc',
  },
  tiktak: {
    primary: '#92400e',
    secondary: '#451a03',
    accent: '#fde68a',
    skin: '#d99a63',
    hair: '#57534e',
    build: 'medium',
    weapon: 'bomb',
    headgear: 'goggles',
    back: 'tank',
    eyes: '#78350f',
  },
  pansuman: {
    primary: '#15803d',
    secondary: '#f1f5f9',
    accent: '#ef4444',
    skin: '#f0c9a2',
    hair: '#14532d',
    build: 'medium',
    weapon: 'medkit',
    headgear: 'cap',
    back: 'pack',
    eyes: '#166534',
  },
  dinamit: {
    primary: '#b91c1c',
    secondary: '#450a0a',
    accent: '#fecaca',
    skin: '#8d5524',
    hair: '#1c1917',
    build: 'medium',
    weapon: 'dynamite',
    headgear: 'goggles',
    back: 'drum',
    eyes: '#450a0a',
  },
  miknatis: {
    primary: '#0e7490',
    secondary: '#083344',
    accent: '#7dd3fc',
    skin: '#bcd3dd',
    hair: '#164e63',
    build: 'heavy',
    weapon: 'magnet',
    headgear: 'visor',
    back: 'coil',
    eyes: '#155e75',
  },
};
